#### 1. Create a NumPy array from 1 to 20.

In [6]:
import numpy as np
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


#### 2. Create a 4×4 matrix of zeros.

In [10]:
b=np.zeros((4,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 3. Create a 3×3 identity matrix.

In [15]:
b=np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 4. Find sum, mean, std, max, and min of an array. (Aggregate Functions)

In [129]:
a=np.array([10,20,30,40])
print(np.sum(a))
print(np.mean(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))

100
25.0
11.180339887498949
40
10


#### 5. Reshape a 1D array of 12 elements into 3×4.

In [28]:
a=np.arange(1,13)
b=a.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 6. Generate 10 random integers between 1 and 100.

In [43]:
r=np.random.randint(1,101,10)
print(r)

[31 28 16 70 74 91 19 40 56 48]


#### 7. Sort an array in ascending order.
Sort a 1D array in ascending order.
Sort a 2D array row-wise.
Sort a 2D array column-wise.

In [133]:
a=np.array([1,4,3,5,7,6,2,8])
s=np.sort(a)
print(s)

d=np.array([
    [4,6,2],
    [8,3,7]
])
print("row-wise sort : ")
print(np.sort(d,axis=1))
print("column-wise sort :")
print(np.sort(d,axis=0))

[1 2 3 4 5 6 7 8]
row-wise sort : 
[[2 4 6]
 [3 7 8]]
column-wise sort :
[[4 3 2]
 [8 6 7]]


#### 8. Filter numbers greater than 50.

In [57]:
a=np.array([101,50,55,40,20,60,57,33,45,51])
b=a[a>50]
print(b)

[101  55  60  57  51]


#### 9. Find square root of all elements in an array.

In [59]:
a=np.arange(1,11)
b=np.sqrt(a)
print(b)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


#### 10. Create two arrays and perform all arithmetic operations.

In [62]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print("sum :",a+b)
print("sub :",a-b)
print("multi :",a*b)
print("div :",a/b)

sum : [5 7 9]
sub : [-3 -3 -3]
multi : [ 4 10 18]
div : [0.25 0.4  0.5 ]


#### 11. Create a NumPy array containing only even numbers from 2 to 20.

In [66]:
a=np.arange(2,21,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


#### 12. Create a 4×4 matrix filled with ones.

In [68]:
a=np.ones((4,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 13. Create a 2×3 array where all elements are 7

In [74]:
a=np.full((2,3),7)
print(a)

[[7 7 7]
 [7 7 7]]


#### 14. Create a random array of 5 floating-point numbers.

In [94]:
a = np.random.uniform(1,10,5)
print(a)

b=np.random.random(5)
print(b)

c = np.round(np.random.uniform(1,10,5),2)
print(c)

[5.38406639 3.521146   4.1011594  1.16176463 2.38963435]
[0.87872562 0.71906911 0.52436796 0.5059611  0.13947646]
[2.31 4.3  9.52 3.59 2.09]


#### 15. Create a 3×4 array and find its shape.

In [ ]:
a=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [8,9,1,2]
])
print(a.shape)


(3, 4)
2


#### 16. Find the dimension of a 2D array.

In [113]:
print(a.ndim)

2


#### 17. Add 5 grace marks to all students.

In [114]:
student=np.array([87,70,80,69,90])
print(student + 5)

[92 75 85 74 95]


#### 18. Universal Functions (ufuncs)

In [119]:
a=np.array([87,70,80,69,90])
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))


b=np.array([12.475,13.65,14.777,43.234,57.987])
print(np.round(b))
print(np.floor(b))
print(np.ceil(b))


[9.32737905 8.36660027 8.94427191 8.30662386 9.48683298]
[6.07603023e+37 2.51543867e+30 5.54062238e+34 9.25378173e+29
 1.22040329e+39]
[4.46590812 4.24849524 4.38202663 4.2341065  4.49980967]
[-0.82181784  0.77389068 -0.99388865 -0.11478481  0.89399666]
[ 0.56975033  0.6333192  -0.11038724  0.99339038 -0.44807362]
[-1.44241747  1.22195992  9.00365495 -0.11554855 -1.99520041]
[12. 14. 15. 43. 58.]
[12. 13. 14. 43. 57.]
[13. 14. 15. 44. 58.]


#### 19. Create a copy of an array and modify it.

In [127]:
a=np.array([1,2,3,4,5])
b=np.copy(a)

b[2]=6
print(a)
print(b)

[1 2 3 4 5]
[1 2 6 4 5]


#### 20. Filtering and Boolean Indexing
##### i) Print all even numbers from an array.<br> ii)Print all odd numbers from an array.<br> iii)Print all elements less than the mean.<br> iv)Replace all values greater than 50 with 100.<br> v) Find elements between 20 and 60.<br> vi) Count how many values are greater than 30.<br> vii) Remove all negative numbers.<br> viii)Replace negative numbers with 0.<br>ix) Print numbers divisible by 5.

In [177]:
a=np.array([1,3,79,2,5,88,7,8,76,6,9,10,55,13,14,12,11,99,15,17,18])
#i)
print("even :",a[a%2==0])
#ii)  
print("\nodd :",a[a%2==1])
#iii)
print("\nelements less than the mean : ",a[a < np.mean(a)])
#iv)
a[a>50]=100
print("\nvalues greater than 50 with 100 :",a)


a=np.array([1,3,79,2,5,88,7,8,76,6,33,9,45,10,55,13,14,12,11,99,15,17,18])
#v)
print("\nelements between 20 and 60 :",a[(a>=20) & (a<=60)])
#vi)
print("\nCount how many values are greater than 30 :",len(a[a>30]))
c=np.array([1,4,6,2,-2,5,-7,-10,11,-14])
#vii)
print("\nRemove all negative numbers :",c[c>0])
#viii)
c[c<0]=0
print("\nReplace negative numbers with 0 :",c)
#ix)
d=np.array([1,10,3,5,20,4,15,7,17,25])
print("\nPrint numbers divisible by 5 :",d[d%5==0])



even : [ 2 88  8 76  6 10 14 12 18]

odd : [ 1  3 79  5  7  9 55 13 11 99 15 17]

elements less than the mean :  [ 1  3  2  5  7  8  6  9 10 13 14 12 11 15 17 18]

values greater than 50 with 100 : [  1   3 100   2   5 100   7   8 100   6   9  10 100  13  14  12  11 100
  15  17  18]

elements between 20 and 60 : [33 45 55]

Count how many values are greater than 30 : 7

Remove all negative numbers : [ 1  4  6  2  5 11]

Replace negative numbers with 0 : [ 1  4  6  2  0  5  0  0 11  0]

Print numbers divisible by 5 : [10  5 20 15 25]
